<section>
	<h3>Qui sommes nous?</h3>

	<p>Notre Agence de voyage, spécialisée dans le voyage et le tourisme a été fondé en 2018 par notre directeur actuel mr MONESMA Antoine.
	C'est avec une équipe solide et dynamique que nous mettons tout en oeuvre pour offrir au client LE VOYAGE de leur rêves et notre premier objectif est de pouvoir rendre accessible ces voyages avec la mise en place de devis permettant des prix parmis les plus attractifs du web.</p>
	<p>Notre siège social se situe à Paris et nous sommes éventuellement accessible par téléphone.
	Ces donc plusieurs centaines de destination à votre disposition et un large choix d'hotel avec options de sorties.
	Notre agence est très pointilleuse sur le bien-être du client et sa satisfaction! Pour le moment le pari est plutôt bien réussit avec un taux de 97% de satisfaction. Nous souhaitons tout de même atteindre les 100% pour faire valoir les valeurs de nos engagements.
	</p>
</section>