<section>
	<h3>Contact</h3>
	<p>Pour toute demande de devis veuillez remplir le formulaire ci-dessous:</p>
</section>
<section id="form">
	
	<form method="POST" action="contact.php">

<div class="form">
	<label for="Name">Votre nom: </label>
   	<input type="text" name="Name" id="Name" />
</div>
<div class="form">
   	<label for="Mail">Votre mail: </label>
   	<input type="text" name="Mail" id="Mail" />
</div>
<div class="form">
      <label for="Phones">Telephone: </label>
      <input type="text" name="Phones" id="Phones" />
</div>
<div class="form">      
   	<label for="Contenus">Votre demande: </label>
   	<textarea placeholder="votre demande de devis!" name="Contenus" id="Contenus"></textarea>
</div>
<div class="form"> 
   	<input type="submit" name="envoyer" id="envoyer" />
</div>
	</form>
</section>