<figure>
		<a href="#"><img src="img/promo.jpg" alt="offre"></a>
		<figcaption>Pour toute commande effectuée avant le 25 décembre</figcaption>
	</figure>
	<flexslider>
	
		<div class="flexslider container">
  <ul class="slides">
    <li>
      <img src="img/slider/usa.jpg" alt="slide1" />
    </li>
    <li>
      <img src="img/slider/grece.jpg" alt="slide2" />
    </li>
      <li>
      <img src="img/slider/paris.jpg" alt="slide3" /> 
    </li>
    <li>
      <img src="img/slider/arg.jpg" alt="slide4" />
    </li>
    <li>
      <img src="img/slider/london.jpg" alt="slide5" />
    </li>
  </ul>
</div>

	</flexslider>

<section class="container">
	<h3>Bienvenue chez Hollidays Booking</h3>
	<p>Envi de voyager, vous évader et pouvoir décompresser? Nous avons la solution à votre recherche.
	<br>En effet, Hollidays Booking a une multitude de destinations à vous proposer à des tarifs imbattables!<br>
	Que ce soit dans n'importe quel continent, à n'importe quel période de l'année, vous pouvez faire appel à nos conseillers touristiques qui vous guiderons vers les plus belles destinations à travers le monde.
	<br>Nous possédons aussi un grand réseau en partenariat avec des compagnies aériennes permettant d'avoir des prix bas et de pouvoir ainsi satisfaire au mieux votre trajet.
	<br>Nous séléctionnons aussi pour vous, des hotels au meilleur rapport qualitée prix, vous offrant détentes et loisirs et bon emplacement.
	<br>Alors si vous êtes tentés, n'attendez plus! Nos offres sont consultables sur notre site dans la rubrique <strong>Nos offres</strong>.
	<br>N'hésitez pas à profiter de nos promotions dans la rubrique <strong>Nos promotions</strong>.</p>
	<p><em>L'équipe Hollidays Booking</em></p>
</section>
