<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" type="text/css" href="fontawesome/css/all.min.css">

<link rel="stylesheet" href="css/flexslider.css" type="text/css">
<link rel="stylesheet" type="text/css" href="fonts/flexslider-icon.ttf">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
<script src="css/jquery.flexslider.js"></script>
<script type="text/javascript" charset="utf-8">
  $(window).load(function() {
    $('.flexslider').flexslider();
  });  
</script>
	<script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script type="text/javascript" src="js/api.js"></script>
	
	<link rel="stylesheet" type="text/css" href="css/main.css">
	
	<title>Hollidays Booking</title>

</head>
<body>
	<header class="container">
		<h1>Hollidays Booking</h1>
		<h2>Les vacances à prix gagnants!</h2>

		<nav>
			<ul>
				<li><a href="agence.php">Qui sommes nous?</a></li>
				<li><a href="offres.php">Nos offres</a></li>
				<li><a href="promotions.php">Nos promotions</a></li>
				<li><a href="contact.php">Contact</a></li>
			</ul>
		</nav>
	</header>
<main class="container">


<?php include $template.'.phtml' ?>


</main>
<footer>
	<h4>Rejoignez nous sur:</h4>
	<a href="#"><i class="fab fa-facebook"></i></a>
	<a href="#"><i class="fab fa-twitter-square"></i></a>
	<a href="#"><i class="fab fa-instagram"></i></a>

	<small><p>Groupe HOLLIDAYS BOOKING SA<br>

Société anonyme au capital de 35 110 000 euros<br>

Siège social : 153, avenue de la découverte

75010 Paris<br>

000 000 000 RCS Paris</p></small>
</footer>
<script type="text/javascript" src="js/main.js"></script>

</body>
</html>