<section>
	<h3>Bienvenue sur nos offres</h3>
	<p>Vous pouvez sélectionner ici nos différentes destinations à travers le monde.</p>
</section>
<section id="formoff" class="container">

<form method="POST" action="offres.php">
    <select name="taskOption" id="taskOption">
  <option value="0">Choisissez</OPTION>";
  <option value="1" id="Europe">Europe</option>
  <option value="2" id="Amerique">Amerique</option>
  <option value="3" id="Oceanie">Oceanie</option>
  <option value="4" id="Asie">Asie</option>
  <option value="5" id="Afrique">Afrique</option>

 
?>
</select>
<input type="submit" name="go" id="run">
</form>
</section> 
<section id="resultat" class="hidden">
	<ul id="continent-list">
    
      
</ul>
</section>

